import board

LED1_PIN = board.IO12
LED2_PIN = board.IO13

ADC1_PIN = board.A5

ROTENC_PIN1 = board.IO12
ROTENC_PIN2 = board.IO13

MATRIX_PIN = board.IO1
#MATRIX_PIXELS = 256
MATRIX_PIXELS = 64

BUTTON_PIN = board.IO6